{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "httpbin.fullname" . }}-netpol
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "httpbin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from AWS Load Balancer Controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: aws-load-balancer-controller
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  # Allow from same namespace (for internal communication)
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.namespaceSelector.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS for external dependencies (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP for external dependencies (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 80
{{- end }}